export const STORE_HOME_INFO = 'STORE_HOME_INFO'
export const ADD_TO_CART = 'ADD_TO_CART'
export const FLASH_SALE = 'FLASH_SALE'
export const ADD_CART = 'ADD_CART'
export const SET_SITES = 'SET_SITES'
